### ISSUE TITLE
HD5 Writable error

### ISSUE THREAD

**Issue by adelavega** [poldracklab/fitlins#105]
I'm getting the following error when running fitlins:

```
ERROR:nipype.workflow:Node _l1_model61 failed to run on host 99c5798a0bdf.
190207-17:51:32,776 nipype.workflow ERROR:
	 Saving crash info to /data/crash-20190207-175132-root-_l1_model61-45897725-e035-4beb-9f98-2757b4f391d0.pklz
Traceback (most recent call last):
  File "/opt/conda/envs/neuro/lib/python3.6/site-packages/nipype/pipeline/plugins/multiproc.py", line 69, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/opt/conda/envs/neuro/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 473, in run
    result = self._run_interface(execute=True)
  File "/opt/conda/envs/neuro/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 557, in _run_interface
    return self._run_command(execute)
  File "/opt/conda/envs/neuro/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 637, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/opt/conda/envs/neuro/lib/python3.6/site-packages/nipype/interfaces/base/core.py", line 369, in run
    runtime = self._run_interface(runtime)
  File "/src/fitlins/fitlins/interfaces/nistats.py", line 62, in _run_interface
    sparse = pd.read_hdf(info['sparse'], key='sparse').rename(
  File "/opt/conda/envs/neuro/lib/python3.6/site-packages/pandas/io/pytables.py", line 394, in read_hdf
    return store.select(key, auto_close=auto_close, **kwargs)
  File "/opt/conda/envs/neuro/lib/python3.6/site-packages/pandas/io/pytables.py", line 741, in select
    return it.get_result()
  File "/opt/conda/envs/neuro/lib/python3.6/site-packages/pandas/io/pytables.py", line 1483, in get_result
    results = self.func(self.start, self.stop, where)
  File "/opt/conda/envs/neuro/lib/python3.6/site-packages/pandas/io/pytables.py", line 734, in func
    columns=columns)
  File "/opt/conda/envs/neuro/lib/python3.6/site-packages/pandas/io/pytables.py", line 2937, in read
    start=_start, stop=_stop)
  File "/opt/conda/envs/neuro/lib/python3.6/site-packages/pandas/io/pytables.py", line 2489, in read_array
    ret = node[0][start:stop]
  File "/opt/conda/envs/neuro/lib/python3.6/site-packages/tables/vlarray.py", line 671, in __getitem__
    return self.read(start, stop, step)[0]
  File "/opt/conda/envs/neuro/lib/python3.6/site-packages/tables/vlarray.py", line 811, in read
    listarr = self._read_array(start, stop, step)
  File "tables/hdf5extension.pyx", line 2106, in tables.hdf5extension.VLArray._read_array
ValueError: cannot set WRITEABLE flag to True of this array
```

It looks like it might be related to nipype, but it's not clear.

**Comment by adelavega** [comment]
Looks like downgrading to nipype 1.15 fixes the problem.

**Comment by effigies** [comment]
Yup. See PyTables/PyTables#717. Submitted a patch over in #106.
