### ISSUE TITLE
Smoothing does not accept "l<N>" level specification

### ISSUE THREAD

**Issue by effigies** [poldracklab/fitlins#156]
`--smoothing 5` results in:

```
Traceback (most recent call last):
  File "/anaconda3/envs/jupyter/bin/fitlins", line 11, in <module>
    load_entry_point('fitlins', 'console_scripts', 'fitlins')()
  File "/Users/markiewicz/Projects/crn/fitlins/fitlins/cli/run.py", line 212, in main
    sys.exit(run_fitlins(sys.argv[1:]))
  File "/Users/markiewicz/Projects/crn/fitlins/fitlins/cli/run.py", line 181, in run_fitlins
    smoothing=opts.smoothing,
  File "/Users/markiewicz/Projects/crn/fitlins/fitlins/workflows/base.py", line 87, in init_fitlins_wf
    raise ValueError(f"Invalid smoothing level {smoothing_level}")
ValueError: Invalid smoothing level l1
```

Related: #134. #135

**Comment by adelavega** [comment]
This is the offending logic:
```
        if (smoothing_level.startswith("l") and
                int(smoothing_level.strip("l")) > len(model_dict)):
            raise ValueError(f"Invalid smoothing level {smoothing_level}")
```

should be: `len(model_dict['Steps'])`

**Comment by effigies** [comment]
Cool, thanks.
