### ISSUE TITLE
ValueError: Built path is not a valid BIDS filename.

### ISSUE THREAD

**Issue by adelavega** [poldracklab/fitlins#179]
```
ERROR:nipype.workflow:Saving crash info to /work/crash-20190920-195640-root-_ds_model_warning1-3fee3f5a-e79a-4af5-9c4e-31d81838c1c2.txt
Traceback (most recent call last):
  File "/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/nipype/pipeline/plugins/multiproc.py", line 316, in _send_procs_to_workers
    self.procs[jobid].run(updatehash=updatehash)
  File "/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 472, in run
    result = self._run_interface(execute=True)
  File "/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 563, in _run_interface
    return self._run_command(execute)
  File "/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 643, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/nipype/interfaces/base/core.py", line 377, in run
    outputs = self.aggregate_outputs(runtime)
  File "/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/nipype/interfaces/base/core.py", line 455, in aggregate_outputs
    predicted_outputs = self._list_outputs()
  File "/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/fitlins/interfaces/bids.py", line 536, in _list_outputs
    base_dir, layout.build_path(ents, path_patterns))
  File "/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/bids/layout/layout.py", line 1213, in build_path
    "spec-compliant.".format(built))
ValueError: Built path sub-NDARAC904DMU/sub-NDARAC904DMU_task-movieDM_snippet.html is not a valid BIDS filename. Please make sure all provided entity values are spec-compliant.
```

fitlins seems a bit unhappy with itself. this is assuming the `TR` fix #178

**Comment by adelavega** [comment]
This also happens with another dataset with a run `id` so it's not that:

```
ValueError: Built path sub-rid000005/sub-rid000005_task-life_run-2_snippet.html is not a valid BIDS filename. Please make sure all provided entity values are spec-compliant.
```

**Comment by effigies** [comment]
Recent update from Tal. We'll need to add "validate=False" or something to `build_path`.

**Comment by adelavega** [comment]
Ok, I will give that a shot

**Comment by adelavega** [comment]
That worked. I'll add a PR for this (although I think the `pybids` release will be helpful so the tests run against that new change).
