### ISSUE TITLE
AttributeError: 'RunNode' object has no attribute 'nodes'

### ISSUE THREAD

**Issue by Meishai96** [poldracklab/fitlins#222]
**Hello,**

**I am a new beginner of fitlins. I was trying to run the first level of my fmriprep processed data (in bids format), however, it stopped at an error after a few minutes, as below:**

docker run --rm -it -v /Users/meishan/Documents/fmri_prep_test2/Nifti_data/sub-001:/bids:ro -v /Users/meishan/Documents/fmri_prep_test2/output/sub-001/fmriprep:/prep:ro -v /Users/meishan/Documents/fmri_prep_test2/analyzed/sub-001:/out -v /Users/meishan/Documents/fmri_prep_test2:/scratch poldracklab/fitlins:latest /bids /out dataset -d /prep -w /work
Traceback (most recent call last):
  File "/opt/miniconda-latest/envs/neuro/bin/fitlins", line 8, in <module>
    sys.exit(main())
  File "/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/fitlins/cli/run.py", line 272, in main
    sys.exit(run_fitlins(sys.argv[1:]))
  File "/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/fitlins/cli/run.py", line 234, in run_fitlins
    smoothing=opts.smoothing, drop_missing=opts.drop_missing,
  File "/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/fitlins/workflows/base.py", line 25, in init_fitlins_wf
    model_dict = specs.run().outputs.model_spec
  File "/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/nipype/interfaces/base/core.py", line 382, in run
    runtime = self._run_interface(runtime)
  File "/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/fitlins/interfaces/bids.py", line 114, in _run_interface
    models = auto_model(layout)
  File "/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/bids/analysis/auto_model.py", line 66, in auto_model
    for n in run_nodes.nodes:
AttributeError: 'RunNode' object has no attribute 'nodes'

**Can anyone tell me how should I find the 'nodes' that seemed missing or how to fix this? Tons of thanks!!**

**Comment by adelavega** [comment]
This looks like a potential bug with pybids's auto_model feature, which creates a model specification for you that is fit with this dataset. 

It's hard to say though, without knowing specifically what your inputs look like. I notice that you are specifying a single subject directory as input: ` /Users/meishan/Documents/fmri_prep_test2/Nifti_data/sub-001:/bids:`.

Is this a complete bids-valid dataset?

You could also try specifying a model to run, rather than the default mode of having one generated for you. 

Here's some example models that you could adapt: https://github.com/poldracklab/fitlins/tree/master/examples/models

**Comment by Meishai96** [comment]
> This looks like a potential bug with pybids's auto_model feature, which creates a model specification for you that is fit with this dataset.
> 
> It's hard to say though, without knowing specifically what your inputs look like. I notice that you are specifying a single subject directory as input: ` /Users/meishan/Documents/fmri_prep_test2/Nifti_data/sub-001:/bids:`.
> 
> Is this a complete bids-valid dataset?
> 
> You could also try specifying a model to run, rather than the default mode of having one generated for you.
> 
> Here's some example models that you could adapt: https://github.com/poldracklab/fitlins/tree/master/examples/models

Thank you the example models are super useful! I tried as you said to specify a model (it took me a while to learn about model specification) by myself but still, the same error came out:
(base) Meishans-iMac:~ meishan$ docker run --rm -it -v /Users/meishan/Documents/BIDS_test3/BIDS_valid:/bids:ro -v /Users/meishan/Documents/fmri_prep_test2/prep/sub-001/:/prep:ro -v /Users/meishan/Documents/fmri_prep_test2/analyzed/sub-001:/out -v /Users/meishan/Documents/fmri_prep_test2:/scratch poldracklab/fitlins:latest -v -q  -d /prep -w /scratch  /bids /out run
Traceback (most recent call last):
  File "/opt/miniconda-latest/envs/neuro/bin/fitlins", line 8, in <module>
    sys.exit(main())
  File "/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/fitlins/cli/run.py", line 272, in main
    sys.exit(run_fitlins(sys.argv[1:]))
  File "/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/fitlins/cli/run.py", line 234, in run_fitlins
    smoothing=opts.smoothing, drop_missing=opts.drop_missing,
  File "/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/fitlins/workflows/base.py", line 25, in init_fitlins_wf
    model_dict = specs.run().outputs.model_spec
  File "/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/nipype/interfaces/base/core.py", line 382, in run
    runtime = self._run_interface(runtime)
  File "/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/fitlins/interfaces/bids.py", line 114, in _run_interface
    models = auto_model(layout)
  File "/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/bids/analysis/auto_model.py", line 66, in auto_model
    for n in run_nodes.nodes:
AttributeError: 'RunNode' object has no attribute 'nodes'

This is my bids folder:(This folder passed the BIDS test when I processed the fmriprep..)
![image](https://user-images.githubusercontent.com/62561104/80240502-ed3cef80-862f-11ea-9ae3-cd706248ce0a.png)
