### ISSUE TITLE
nipype.utils.filemanip.makedirs function removed

### ISSUE THREAD

**Issue by bpinsard** [poldracklab/fitlins#246]
On a fresh pip install of fitlins, I have the following error.
It seems that this function was removed from nipype and the current `setup.cfg` gets the latest nipype release.

```
$ fitlins
Traceback (most recent call last):
  File "/home/basile/anaconda3/envs/fitlins/bin/fitlins", line 5, in <module>
    from fitlins.cli.run import main
  File "/home/basile/anaconda3/envs/fitlins/lib/python3.8/site-packages/fitlins/cli/run.py", line 24, in <module>
    from ..workflows import init_fitlins_wf
  File "/home/basile/anaconda3/envs/fitlins/lib/python3.8/site-packages/fitlins/workflows/__init__.py", line 6, in <module>
    from .base import init_fitlins_wf
  File "/home/basile/anaconda3/envs/fitlins/lib/python3.8/site-packages/fitlins/workflows/base.py", line 6, in <module>
    from ..interfaces.bids import (
  File "/home/basile/anaconda3/envs/fitlins/lib/python3.8/site-packages/fitlins/interfaces/bids.py", line 10, in <module>
    from nipype.utils.filemanip import makedirs, copyfile
ImportError: cannot import name 'makedirs' from 'nipype.utils.filemanip' (/home/basile/anaconda3/envs/fitlins/lib/python3.8/site-packages/nipype/utils/filemanip.py)
```

**Comment by effigies** [comment]
It's fixed in master. It looks like it's been a long time since a release...

@adelavega If you confirm that neuroscout works with the latest master, I can release.

**Comment by adelavega** [comment]
I can check tomorrow, no problem, but don't feel the need to wait for me. Currently I'm building off master anyways, so it most likely does work.
