### ISSUE TITLE
ValueError: 'desc' is not a recognized entity.

### ISSUE THREAD

**Issue by bpinsard** [poldracklab/fitlins#247]
Installed the fitlins master branch and pybids (pip and github) and I get the following error.

```
200729-12:48:57,139 nipype.workflow ERROR:
	 could not run node: fitlins_wf.loader
Traceback (most recent call last):
  File "/home/basile/anaconda3/envs/fitlins/bin/fitlins", line 8, in <module>
    sys.exit(main())
  File "/home/basile/anaconda3/envs/fitlins/lib/python3.8/site-packages/fitlins/cli/run.py", line 271, in main
    sys.exit(run_fitlins(sys.argv[1:]))
  File "/home/basile/anaconda3/envs/fitlins/lib/python3.8/site-packages/fitlins/cli/run.py", line 263, in run_fitlins
    analysis.setup(**selectors)
  File "/home/basile/anaconda3/envs/fitlins/lib/python3.8/site-packages/bids/analysis/analysis.py", line 98, in setup
    step.setup(input_contrasts, drop_na=drop_na, **selectors)
  File "/home/basile/anaconda3/envs/fitlins/lib/python3.8/site-packages/bids/analysis/analysis.py", line 255, in setup
    collections = self.layout.get_collections(self.level, drop_na=drop_na,
  File "/home/basile/anaconda3/envs/fitlins/lib/python3.8/site-packages/bids/layout/layout.py", line 1172, in get_collections
    index = load_variables(self, types=types, levels=level,
  File "/home/basile/anaconda3/envs/fitlins/lib/python3.8/site-packages/bids/variables/io.py", line 93, in load_variables
    dataset = _load_time_variables(layout, dataset, scope=scope, **_kwargs)
  File "/home/basile/anaconda3/envs/fitlins/lib/python3.8/site-packages/bids/variables/io.py", line 183, in _load_time_variables
    images = layout.get(return_type='object', scope=scope, extension=exts, **selectors)
  File "/home/basile/anaconda3/envs/fitlins/lib/python3.8/site-packages/bids/layout/layout.py", line 983, in get
    raise ValueError(msg + "If you're sure you want to impose "
ValueError: 'desc' is not a recognized entity. If you're sure you want to impose this constraint, set invalid_filters='allow'.
```

**Comment by sitek** [comment]
I have the same error when running an environment following the [manual installation](https://fitlins.readthedocs.io/en/latest/installation.html#manually-prepared-environment-python-3-6)

**Comment by effigies** [comment]
What's your model? It looks like you put desc in the input section, and I suppose that we don't use derivatives when constructing the model.

**Comment by arovai** [comment]
Resurrecting this, I have the same issue with version v0.11.0, which is the latest docker build on dockerhub/poldracklab.
The model file is basically the same as in the examples (the one in `fitlins/examples/models/ds000003/models`), with task names adapted to my dataset.
In particular, Input doesn't contain 'desc', just the task name.
Any guess?

**Comment by effigies** [comment]
Can you share the model as well as your command and file listing for your input datasets?

**Comment by arovai** [comment]
Shame on me, I just can't reproduce it right now. I am completely puzzled.
Apologizes for the trouble!
