### ISSUE TITLE
key error "trial_type"

### ISSUE THREAD

**Issue by adelavega** [poldracklab/fitlins#257]
```
Traceback (most recent call last):
  File "/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/nipype/pipeline/plugins/multiproc.py", line 69, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 479, in run
    result = self._run_interface(execute=True)
  File "/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 585, in _run_interface
    return self._run_command(execute)
  File "/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 678, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/nipype/interfaces/base/core.py", line 382, in run
    runtime = self._run_interface(runtime)
  File "/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/fitlins/interfaces/nistats.py", line 110, in _run_interface
    drift_model=drift_model,
  File "/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/nistats/design_matrix.py", line 350, in make_first_level_design_matrix
    oversampling)
  File "/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/nistats/design_matrix.py", line 221, in _convolve_regressors
    trial_type, onset, duration, modulation = check_events(events)
  File "/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/nistats/experimental_paradigm.py", line 58, in check_events
    trial_type = np.array(events['trial_type'])
  File "/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/pandas/core/frame.py", line 2980, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2899, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 107, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 131, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1607, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1614, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'trial_type'
```

So far stumped on this one. Running the latest master `fitlins` and `nistats`. Will dig deeper... (everthing seems to work on the previously release version btw)

**Comment by adelavega** [comment]
ah, I think the BIDS Stats model is at fault. It's missing some info. Probably in this scenario we should crash early and throw an exception

**Comment by adelavega** [comment]
hah, this is the offending statsmodel:

```
{
  "Name": "",
  "Description": "",
  "Input": {},
  "Steps": [
    {
      "Level": "Run",
      "Transformations": [],
      "Contrasts": [],
      "Model": {
        "X": []
      }
    },
    {
      "Level": "Subject",
      "DummyContrasts": {
        "Type": "FEMA"
      }
    },
    {
      "Level": "Dataset",
      "DummyContrasts": {
        "Type": "t"
      }
    }
  ]
}
```

**Comment by adelavega** [comment]
turns out the empty BIDS model was a separate issue. 

It looks to me that the issue is for `sparse` events nistats expects a `trail_type` column, and a "long" format.

e.g.:
```
      amplitude               condition datatype  duration       onset  run session subject suffix   task
0     -0.054036           a_comp_cor_00     func  2.000001    0.000000    1   movie      18   bold  movie
1      0.035110           a_comp_cor_00     func  2.000001    2.000001    1   movie      18   bold  movie
2     -0.067291           a_comp_cor_00     func  2.000001    4.000001    1   movie      18   bold  movie
3      0.008029           a_comp_cor_00     func  2.000001    6.000002    1   movie      18   bold  movie
4      0.009744           a_comp_cor_00     func  2.000001    8.000002    1   movie      18   bold  movie
...         ...                     ...      ...       ...         ...  ...     ...     ...    ...    ...
3151   0.151339  framewise_displacement     func  2.000001  892.000272    1   movie      18   bold  movie
3152   0.188426  framewise_displacement     func  2.000001  894.000273    1   movie      18   bold  movie
3153   0.106226  framewise_displacement     func  2.000001  896.000273    1   movie      18   bold  movie
3154   0.125425  framewise_displacement     func  2.000001  898.000274    1   movie      18   bold  movie
3155   0.149661  framewise_displacement     func  2.000001  900.000274    1   movie      18   bold  movie
```

However, recent changes to pybids result in the following:

```
     run       onset  duration   task session datatype subject suffix  a_comp_cor_00  framewise_displacement
0      1    0.000000  2.000001  movie   movie     func      01   bold       0.040195                     NaN
1      1    2.000001  2.000001  movie   movie     func      01   bold      -0.002651                0.110298
2      1    4.000001  2.000001  movie   movie     func      01   bold      -0.057618                0.114467
3      1    6.000002  2.000001  movie   movie     func      01   bold       0.092859                0.147994
4      1    8.000002  2.000001  movie   movie     func      01   bold      -0.052855                0.205297
..   ...         ...       ...    ...     ...      ...     ...    ...            ...                     ...
446    1  892.000272  2.000001  movie   movie     func      01   bold       0.009815                0.137125
447    1  894.000273  2.000001  movie   movie     func      01   bold      -0.051044                0.164338
448    1  896.000273  2.000001  movie   movie     func      01   bold      -0.023322                0.121573
449    1  898.000274  2.000001  movie   movie     func      01   bold       0.008527                0.195751
450    1  900.000274  2.000001  movie   movie     func      01   bold      -0.082895                0.215583
```

I think the only way to fix this is to pivot this df into long format using `trial_type` as a key.
