### ISSUE TITLE
Error on fitlins_wf.loader

### ISSUE THREAD

**Issue by hechlera** [poldracklab/fitlins#258]
We are currently implementing a new fMRI pipeline in the lab and are testing FitLins as a follow up to MRIQC and fMRIPrep. I am running FitLins through Docker on a fMRIPrep-processed dataset (simple output, no cifti). BIDS validation passes for both the raw data and the derivatives files. FitLins is ver 0.7.0 (BIDS 1.1.0), fMRIPrep is ver 20.1.1 (BIDS 1.1.1). I carefully matched the model file to the online examples and at minimum, it passes json.load() when testing for obvious errors.

Before any real processing happens, I get the following errors:

######################

201012-10:05:39,305 nipype.utils WARNING:
A newer version (1.5.1) of nipy/nipype is available. You are using 1.5.0
201012-10:05:45,210 nipype.workflow WARNING:
Storing result file without outputs
201012-10:05:45,211 nipype.workflow WARNING:
[Node] Error on “fitlins_wf.loader” (/working_dir/fitlins_wf/loader)
201012-10:05:45,521 nipype.workflow ERROR:
Node loader failed to run on host df292346edbc.
201012-10:05:45,524 nipype.workflow ERROR:
Saving crash info to /working_dir/crash-20201012-100545-UID1541801116-loader-20a1a3c4-0f46-4096-a162-6bfae5e11684.txt
Traceback (most recent call last):
File “/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/nipype/pipeline/plugins/multiproc.py”, line 148, in init
mp_context=mp_context,
TypeError: init() got an unexpected keyword argument ‘initializer’

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File “/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/nipype/pipeline/plugins/multiproc.py”, line 67, in run_node
result[“result”] = node.run(updatehash=updatehash)
File “/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py”, line 516, in run
result = self._run_interface(execute=True)
File “/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py”, line 635, in _run_interface
return self._run_command(execute)
File “/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py”, line 741, in _run_command
result = self._interface.run(cwd=outdir)
File “/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/nipype/interfaces/base/core.py”, line 397, in run
runtime = self._run_interface(runtime)
File “/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/fitlins/interfaces/bids.py”, line 221, in _run_interface
self._load_level1(runtime, analysis)
File “/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/fitlins/interfaces/bids.py”, line 304, in _load_level1
names.extend(col for col in dense.columns if col.startswith(‘non_steady_state’))
File “/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/fitlins/interfaces/bids.py”, line 304, in
names.extend(col for col in dense.columns if col.startswith(‘non_steady_state’))
AttributeError: ‘tuple’ object has no attribute ‘startswith’

201012-10:05:47,518 nipype.workflow ERROR:
could not run node: fitlins_wf.loader
Traceback (most recent call last):
File “/opt/miniconda-latest/envs/neuro/bin/fitlins”, line 8, in
sys.exit(main())
File “/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/fitlins/cli/run.py”, line 271, in main
sys.exit(run_fitlins(sys.argv[1:]))
File “/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/fitlins/cli/run.py”, line 265, in run_fitlins
write_full_report(report_dict, run_context, deriv_dir)
File “/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/fitlins/viz/reports.py”, line 132, in write_full_report
Path(target_file).write_text(html)
File “/opt/miniconda-latest/envs/neuro/lib/python3.6/pathlib.py”, line 1215, in write_text
with self.open(mode=‘w’, encoding=encoding, errors=errors) as f:
File “/opt/miniconda-latest/envs/neuro/lib/python3.6/pathlib.py”, line 1183, in open
opener=self._opener)
File “/opt/miniconda-latest/envs/neuro/lib/python3.6/pathlib.py”, line 1037, in _opener
return self._accessor.open(self, flags, mode)
File “/opt/miniconda-latest/envs/neuro/lib/python3.6/pathlib.py”, line 387, in wrapped
return strfunc(str(pathobj), *args)
FileNotFoundError: [Errno 2] No such file or directory: ‘/output/fitlins/reports/model-3cond.html’

##################

Following some (layman-level) digging, it seems to me the AttributeError during execution of bids.py is linked to reading input json files (can’t make out which) where at some point during transformation to dataframes and reading of columns, a tuple is extracted instead of a single value. All help is very much appreciated!

Best,

André

**Comment by hechlera** [comment]
On the virtual machine through which I access the data, python environment and docker I sadly have no admin privileges (I'll see if I can talk someone into it). Guess I could get the data to local though and try your suggestions this way.

**Comment by effigies** [comment]
You can install [miniconda](https://docs.conda.io/projects/conda/en/latest/user-guide/install/) in your home directory and get a fully user-owned Python environment.

**Comment by hechlera** [comment]
I get the same error again when running without docker. I'll hopefully get to more debugging early next week and keep you updated!

**Comment by hechlera** [comment]
nipypecli output:

################################
Node inputs:

model = {'Name': '3cond', 'Input': {'task': '3cond'}, 'Description': 'EBits main contrasts: rand vs. struct and both vs. base', 'Steps': [{'Level': 'run', 'Transformations': [{'Name': 'Factor', 'Input': ['trial_type']}, {'Name': 'Convolve', 'Input': ['trial_type.rand', 'trial_type.struct', 'trial_type.base']}], 'Model': {'X': ['trial_type.rand', 'trial_type.struct', 'trial_type.base', 'trans_x', 'trans_y', 'trans_z', 'rot_x', 'rot_y', 'rot_z']}, 'DummyContrasts': {'Conditions': ['trial_type.rand', 'trial_type.struct'], 'Type': 't'}, 'Contrasts': [{'Name': 'rand_gt_struct', 'ConditionList': ['trial_type.rand', 'trial_type.struct'], 'Weights': [1, -1], 'Type': 't'}, {'Name': 'struct_gt_rand', 'ConditionList': ['trial_type.rand', 'trial_type.struct'], 'Weights': [-1, 1], 'Type': 't'}]}, {'Level': 'subject', 'DummyContrasts': {'Type': 'FEMA'}}]}
selectors = {'desc': 'preproc', 'space': 'MNI152NLin2009cAsym'}



Traceback:
Traceback (most recent call last):
  File "/RAID1/miniconda3/envs/jupyterhub_py37/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/RAID1/miniconda3/envs/jupyterhub_py37/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
    result = self._run_interface(execute=True)
  File "/RAID1/miniconda3/envs/jupyterhub_py37/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_interface
    return self._run_command(execute)
  File "/RAID1/miniconda3/envs/jupyterhub_py37/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 741, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/RAID1/miniconda3/envs/jupyterhub_py37/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 397, in run
    runtime = self._run_interface(runtime)
  File "/RAID1/miniconda3/envs/jupyterhub_py37/lib/python3.7/site-packages/fitlins/interfaces/bids.py", line 221, in _run_interface
    self._load_level1(runtime, analysis)
  File "/RAID1/miniconda3/envs/jupyterhub_py37/lib/python3.7/site-packages/fitlins/interfaces/bids.py", line 304, in _load_level1
    names.extend(col for col in dense.columns if col.startswith('non_steady_state'))
  File "/RAID1/miniconda3/envs/jupyterhub_py37/lib/python3.7/site-packages/fitlins/interfaces/bids.py", line 304, in <genexpr>
    names.extend(col for col in dense.columns if col.startswith('non_steady_state'))
AttributeError: 'tuple' object has no attribute 'startswith'

#####################

I also ran the (as I assume) critical lines from fitlins/bids.py step by step on my dataset. So essentially the LoadBIDSModel._run_interface() and _load_level1 up unto the line that throws the error and it works fine...but then again I am not yet aware of all the interdepencies in the code.

**Comment by effigies** [comment]
If you run `nipypecli crash` with debugging mode (`-d` for pdb or `-i` for ipdb), then you can look at what `dense.columns` and other values are to help track down the problem.

**Comment by hechlera** [comment]
Ah, I did not use the -r flag in addition to -d. Now we are getting somewhere:

############################

/RAID1/miniconda3/envs/jupyterhub_py37/lib/python3.7/site-packages/fitlins/interfaces/bids.py in _load_level1(self=<fitlins.interfaces.bids.LoadBIDSModel object>, runtime=Bunch(cwd='/home/tumnic/ahechler/data/fitlins_wo...unning interface LoadBIDSModel.",), version=None), analysis=<bids.analysis.analysis.Analysis object>)
    302                 # explicitly listed in the model
    303                 names = [var for var in step.model['x'] if var in dense.columns]
--> 304                 names.extend(col for col in dense.columns if col.startswith('non_steady_state'))
        names.extend = <built-in method extend of list object at 0x7f821eb44370>
        global col = undefined
        global dense.columns = undefined
        global col.startswith = undefined
    305                 dense = dense[names]
    306

/RAID1/miniconda3/envs/jupyterhub_py37/lib/python3.7/site-packages/fitlins/interfaces/bids.py in <genexpr>(.0=<map object>)
    302                 # explicitly listed in the model
    303                 names = [var for var in step.model['x'] if var in dense.columns]
--> 304                 names.extend(col for col in dense.columns if col.startswith('non_steady_state'))
        global names.extend = undefined
        col = ('duration', '')
        global dense.columns = undefined
        col.startswith = undefined
    305                 dense = dense[names]
    306

AttributeError: 'tuple' object has no attribute 'startswith'
> /RAID1/miniconda3/envs/jupyterhub_py37/lib/python3.7/site-packages/fitlins/interfaces/bids.py(304)<genexpr>()
    302                 # explicitly listed in the model
    303                 names = [var for var in step.model['x'] if var in dense.columns]
--> 304                 names.extend(col for col in dense.columns if col.startswith('non_steady_state'))
    305                 dense = dense[names]
    306

############################

The only place where duration might be coming from is the _events.tsv. Mine pretty much perfecty resembles the example in (https://openneuro.org/datasets/ds000003/versions/00001/file-display/sub-01:func:sub-01_task-rhymejudgment_events.tsv), although I used no padding/decimal places if not necessary:

onset	duration	trial_type
0	4	struct
5.5	4	struct
11	4	struct
16.5	4	struct
22	4	rand
[...]

**Comment by effigies** [comment]
Okay, thanks for digging in. I'll see if I can replicate with ds003.

**Comment by tyarkoni** [comment]
Just a guess, but for some reason the column index in `dense` might be a pandas hierarchical index (i.e., `MultiIndex`), in which case iterating might be returning a tuple instead of a string. Not sure why that would be happening though.

**Comment by effigies** [comment]
@hechlera Could you share your events file?

**Comment by hechlera** [comment]
Sure. Here goes:
[sub-p777_task-3cond_events.zip](https://github.com/poldracklab/fitlins/files/5389967/sub-p777_task-3cond_events.zip)
