### ISSUE TITLE
Errors in early steps of fitlins walk-through

### ISSUE THREAD

**Issue by arovai** [poldracklab/fitlins#295]
Hello,
I am trying to follow the step of the [walk-through](https://fitlins.readthedocs.io/en/latest/examples/notebooks/ds003_sample_analysis.html#gallery-examples-notebooks-ds003-sample-analysis-ipynb), but after running the command

```
pip install -q --upgrade "datalad @ git+https://github.com/datalad/datalad@5f5342ce2e63b91d54f75edb87d97129a916d9ef" \
                         "nistats @ git+https://github.com/nistats/nistats.git@b69e127020df05aa8ba540f9a8d799e1dad3d602"
```

I get a bunch of errors:

```
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-zxcl7me1/datalad_d229d12e88f04d57891e8d1b00110d9c/setup.py'"'"'; __file__='"'"'/tmp/pip-install-zxcl7me1/datalad_d229d12e88f04d57891e8d1b00110d9c/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-y2phgfix
         cwd: /tmp/pip-install-zxcl7me1/datalad_d229d12e88f04d57891e8d1b00110d9c/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-zxcl7me1/datalad_d229d12e88f04d57891e8d1b00110d9c/setup.py", line 51, in <module>
        dist = platform.dist()
    AttributeError: module 'platform' has no attribute 'dist'
    ----------------------------------------
WARNING: Discarding git+https://github.com/datalad/datalad@5f5342ce2e63b91d54f75edb87d97129a916d9ef. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement datalad (unavailable) (from versions: 0.2, 0.2.1.dev1, 0.2.1, 0.2.2, 0.2.3, 0.3, 0.3.1, 0.4, 0.4.1, 0.5.0, 0.5.1, 0.6.0.dev1, 0.6.0, 0.7.0, 0.8.0, 0.8.1, 0.9.0, 0.9.1, 0.9.2, 0.9.3, 0.10.0rc1, 0.10.0rc2, 0.10.0rc3, 0.10.0rc4, 0.10.0rc5, 0.10.0, 0.10.1, 0.10.2, 0.10.3.1, 0.11.0, 0.11.1, 0.11.2, 0.11.3, 0.11.4, 0.11.5, 0.11.6, 0.11.7, 0.11.8, 0.12.0rc1, 0.12.0rc2, 0.12.0rc3, 0.12.0rc4, 0.12.0rc5, 0.12.0rc6, 0.12.0, 0.12.1, 0.12.2, 0.12.3, 0.12.4, 0.12.5, 0.12.6, 0.12.7, 0.13.0rc1, 0.13.0rc2, 0.13.0, 0.13.1, 0.13.2, 0.13.3, 0.13.4, 0.13.5, 0.13.6, 0.13.7, 0.14.0rc1, 0.14.0, 0.14.1, 0.14.2, 0.14.3, 0.14.4)
ERROR: No matching distribution found for datalad (unavailable)
```

Any guess?

By the way I just ignored this and, starting from scratch: created the model file and then run

```
datalad install -rg ///labs/poldrack/ds003_fmriprep
fitlins ds003_fmriprep/sourcedata output/ dataset --derivatives $PWD/ds003_fmriprep --model $PWD/model-001_smdl.json --smoothing 5:run -w scratch --n-cpus 3
```

and everything worked nicely.

**Comment by effigies** [comment]
I don't really remember exactly why I pinned those versions. If it works with the latest versions of datalad, then great.
