### ISSUE TITLE
Error: Input entities was not set but it is listed in iterfields

### ISSUE THREAD

**Issue by arovai** [poldracklab/fitlins#296]
Hello!
I am trying to run fitlins on a very simple dataset made of one subject. `fmriprep` run without any problem.

I have tried to make my stats model file as minimalistic as possible:
```

{
  "Name": "test_model001",
  "Description": "",
  "Input": {
    "task": "gas"
  },
  "Steps": [
    {
      "Level": "subject",
      "Model": {
        "X": [
          "trial_type.gas"
        ]
      },
      "Contrasts": [
        {
          "Name": "gas_gt_baseline",
          "ConditionList": [
            "trial_type.gas"
          ],
          "Weights": [1],
          "Type": "t"
        }
      ]
    }
  ]
}
```

Here, `gas` is both the name of the task and the `trial_type` value in my `task-gas_events.tsv`.

The command I use is
`
fitlins $PWD/fmriprep/sourcedata $PWD/output participant --work-dir $PWD/work --derivatives $PWD/fmriprep --model $PWD/model-001_smdl.json
`

I run this from my `test` directory, at which on top level I have the `fmriprep` directory and the `model-001_smdl.json`. Inside `fmriprep`, I have a `sourcedata` directory which is BIDS valid and contain the data from which the fmriprep output was derived.

While this layout is not totally standard, it actually mimics the one I used for my preliminary testing (see #295) for which I had no error.

Here is the full output:

```
Captured warning (<class 'FutureWarning'>): Fetchers from the nilearn.datasets module will be updated in version 0.9 to return python strings instead of bytes and Pandas dataframes instead of Numpy arrays.
210616-16:05:21,899 nipype.workflow ERROR:
	 Node ds_model_warning failed to run on host worker1.
210616-16:05:21,900 nipype.workflow ERROR:
	 Saving crash info to /home/work/projects/test/work/crash-20210616-160521-work-ds_model_warning-6e8e7c48-c077-4946-9406-61e1394cea72.pklz
Traceback (most recent call last):
  File "/home/work/.local/lib/python3.8/site-packages/nipype/pipeline/plugins/multiproc.py", line 292, in _send_procs_to_workers
    num_subnodes = self.procs[jobid].num_subnodes()
  File "/home/work/.local/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 1310, in num_subnodes
    self._check_iterfield()
  File "/home/work/.local/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 1333, in _check_iterfield
    raise ValueError(
ValueError: Input entities was not set but it is listed in iterfields.


When creating this crashfile, the results file corresponding
to the node could not be found.
210616-16:05:21,907 nipype.workflow WARNING:
	 Storing result file without outputs
210616-16:05:21,908 nipype.workflow WARNING:
	 [Node] Error on "fitlins_wf.getter" (/home/work/projects/test/work/fitlins_wf/getter)
210616-16:05:23,851 nipype.workflow ERROR:
	 Node getter failed to run on host worker1.
210616-16:05:23,851 nipype.workflow ERROR:
	 Saving crash info to /home/work/projects/test/work/crash-20210616-160523-work-getter-c84bfa47-caa5-4b12-a385-07d39e28cfc8.pklz
Traceback (most recent call last):
  File "/home/work/.local/lib/python3.8/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/home/work/.local/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
    result = self._run_interface(execute=True)
  File "/home/work/.local/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_interface
    return self._run_command(execute)
  File "/home/work/.local/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 741, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/home/work/.local/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 389, in run
    self._check_mandatory_inputs()
  File "/home/work/.local/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 268, in _check_mandatory_inputs
    raise ValueError(msg)
ValueError: BIDSSelect requires a value for input 'entities'. For a list of required inputs, see BIDSSelect.help()

210616-16:05:25,852 nipype.workflow ERROR:
	 could not run node: fitlins_wf.getter
Traceback (most recent call last):
  File "/home/work/.local/bin/fitlins", line 8, in <module>
    sys.exit(main())
  File "/home/work/.local/lib/python3.8/site-packages/fitlins/cli/run.py", line 294, in main
    sys.exit(run_fitlins(sys.argv[1:]))
  File "/home/work/.local/lib/python3.8/site-packages/fitlins/cli/run.py", line 288, in run_fitlins
    write_full_report(report_dict, run_context, deriv_dir)
  File "/home/work/.local/lib/python3.8/site-packages/fitlins/viz/reports.py", line 132, in write_full_report
    Path(target_file).write_text(html)
  File "/usr/lib/python3.8/pathlib.py", line 1251, in write_text
    with self.open(mode='w', encoding=encoding, errors=errors) as f:
  File "/usr/lib/python3.8/pathlib.py", line 1218, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/usr/lib/python3.8/pathlib.py", line 1074, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/home/work/projects/test/output/fitlins/reports/model-testModel001.html'
```

Sorry for not being able to filter the output for you. I have looked here and there for anything obvious but couldn't find anything, so I decided to copy/paste the whole thing.

Note that I have run the exact same test on a different dataset (different files, different task but basically the same paradigm), without success.

What I am doing wrong here? Thanks for your help :-)

**Comment by arovai** [comment]
Ok, found it...
Basically my model file was inconsistent.
Here is one that worked:

```
{
  "Name": "test_model001",
  "Description": "",
  "Input": {
    "task": "ckcactif"
  },
  "Steps": [
    {
      "Level": "run",
      "Transformations": [
        {
          "Name": "Factor",
          "Input": [
            "trial_type"
          ]
        },
        {
          "Name": "Convolve",
          "Input": ["trial_type.stim"],
          "Model": "spm"
        }
      ],
      "Model": {
        "X": [
          "trial_type.stim",
          "framewise_displacement",
          "trans_x", "trans_y", "trans_z", "rot_x", "rot_y", "rot_z",
          "a_comp_cor_00", "a_comp_cor_01", "a_comp_cor_02",
          "a_comp_cor_03", "a_comp_cor_04", "a_comp_cor_05"
        ]
      },
      "Contrasts": [
        {
          "Name": "stim_vs_baseline",
          "ConditionList": [
            "trial_type.stim"
          ],
          "Weights": [1],
          "Type": "t"
        }
      ]
    }
  ]
}
```

There was another thing to fix but for that I'll open a different issue.
