### ISSUE TITLE
Docker output volume mounted (Windows)

### ISSUE THREAD

**Issue by adelavega** [poldracklab/fitlins#33]
On Windows 10, when fitlins outputs to a mounted volume, there are occasional problems writing the output contrast files. E.g:

```
Error: Traceback (most recent call last):

  File "/opt/conda/envs/neuro/lib/python3.6/site-packages/nipype/pipeline/engine/utils.py", line 106, in nodelist_runner
    result = node.run(updatehash=updatehash)

  File "/opt/conda/envs/neuro/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 480, in run
    result = self._run_interface(execute=True)

  File "/opt/conda/envs/neuro/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 564, in _run_interface
    return self._run_command(execute)

  File "/opt/conda/envs/neuro/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 644, in _run_command
    result = self._interface.run(cwd=outdir)

  File "/opt/conda/envs/neuro/lib/python3.6/site-packages/nipype/interfaces/base/core.py", line 521, in run
    outputs = self.aggregate_outputs(runtime)

  File "/opt/conda/envs/neuro/lib/python3.6/site-packages/nipype/interfaces/base/core.py", line 595, in aggregate_outputs
    predicted_outputs = self._list_outputs()

  File "/src/fitlins/fitlins/interfaces/bids.py", line 367, in _list_outputs
    _copy_or_convert(in_file, out_fname)

  File "/src/fitlins/fitlins/interfaces/bids.py", line 304, in _copy_or_convert
    copyfile(in_file, out_file, copy=True, use_hardlink=True)

  File "/opt/conda/envs/neuro/lib/python3.6/site-packages/nipype/utils/filemanip.py", line 487, in copyfile
    copy_related_files=False)

  File "/opt/conda/envs/neuro/lib/python3.6/site-packages/nipype/utils/filemanip.py", line 471, in copyfile
    shutil.copyfile(originalfile, newfile)

  File "/opt/conda/envs/neuro/lib/python3.6/shutil.py", line 121, in copyfile
    with open(dst, 'wb') as fdst:

FileNotFoundError: [Errno 2] No such file or directory: '/datasets/SherlockMerlin/derivatives/neuroscout/qW/fitlins/sub-34/sub-34_task-MerlinMovie_bold_space-MNI152NLin2009cAsym_contrast-rmse_stat.nii.gz'
```

This problem goes away when outputting within the `fitlins` image.

**Comment by effigies** [comment]
Could you post your whole Docker command, too?

**Comment by adelavega** [comment]
I'm running this through `neuroscout`, so here are the inputs to `main`:

`['/datasets/SherlockMerlin', '/datasets/SherlockMerlin/derivatives/neuroscout/qW', 'dataset', '--model=/datasets/SherlockMerlin/derivatives/neuroscout/qW/model.json', '--exclude=.*neuroscout/(?!qW).*'] `

**Comment by effigies** [comment]
I see. And it is generally populating directories in `SherlockMerlin/derivatives/neuroscout/qW` on the mounted volume?

**Comment by adelavega** [comment]
Yep. All the subject directories are created, and originally (with `MultiProc`) only a small percentage of files were having problem opening.

**Comment by effigies** [comment]
Hmm. I wonder if there's a limit on CIFS of simultaneous open files.

**Comment by effigies** [comment]
But I guess running `Linear` should fix that, and it doesn't. @chrisfilo have you run into a similar issue?

**Comment by chrisfilo** [comment]
yes - I recently encountered some similar and switched to using container storage for working directory

**Comment by effigies** [comment]
Problem is this is derivatives.

**Comment by chrisfilo** [comment]
I have not encountered this. Might be worth looking into instructing docker to use a different mechanism for interacting with host filesystem
